
name: omnifig
long_name: omni-fig

version: '0.1'
url: 'https://github.com/felixludos/omni-fig'

description: 'Universal configuration system for common execution environments'

author: Felix Leeb
author_email: 'felixludos.info@gmail.com'

license: GPL3

readme: 'README.rst'

packages: ['omnifig']

install_requires: ['C3Linearize', 'humpack'] # omnibelt

entry_points:
  console_scripts: 'fig = omnifig.scripts:entry'
