
_meta.script_name: train # name of the script you want to run
# other meta arguments should be inside the "_meta" node (see documentation for details)


# arguments can be overridden here for debug purposes

model.name: debug_model

model.layers: [100, 100, 100]
