
name: deep_fake

description:
  "Example omni-fig project for a deep learning related project - note
  that this project only pretends to actually trained models"


# Note: all paths specified in the project info file (this file), should be relative
# to the project directory (directory containing this file)

related: [] # list of other project names (whose past must be found in the profile's "projects" table)
# related projects are (recursively) loaded before this project is loaded - so this can depend on it's relatives

src: startup.py # this file will be executed when loading this project

