name: Unit-Tests
on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip3 install pytest pytest-github-actions-annotate-failures
    - name: Test with pytest
      run: |
        pytest
